clientes/urls.py
from django.urls import path

from clientes.views import *

urlpatterns = [
    path('', home),
    path('os/', os, name="form_modelform"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientes.urls')),

]

clientes/models.py
from django.db import models
import random
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError


def validate_cpf(value):
    if not value.isdigit():
        raise ValidationError('O CPF deve conter apenas números')


# ---------------------Cadastros primários------------------------
class PecasVeiculo(models.Model):
    pecas_veiculo = models.CharField(max_length=30, verbose_name="Peças do veículo")

    class Meta:
        verbose_name_plural = "02-Cadastro de Peças"

    def __str__(self):
        return self.pecas_veiculo


class TipoVeiculo(models.Model):
    tipoVeiculo = models.CharField(max_length=30, verbose_name="Tipo de veículo")

    class Meta:
        verbose_name_plural = "03-Cadastro de Veículo"

    def __str__(self):
        return self.tipoVeiculo


# -------------------------Cadastro de grupo----------------

class GrupoPecas(models.Model):
    grupo_pecas = models.CharField(max_length=30, verbose_name="Nome do conjunto")
    grupo_description = models.TextField(blank=True, null=False, verbose_name="Descrição do conjunto cadastrado")
    pecas_veiculo = models.ManyToManyField(PecasVeiculo, verbose_name="Peças a serem adicionadas")

    class Meta:
        verbose_name_plural = "04-Cadastro de Sistema"

    def __str__(self):
        return self.grupo_pecas


# ----------------------------Clientes------------------------------------
class Cliente(models.Model):
    cliente_nome = models.CharField(max_length=150, verbose_name='Nome')
    cliente_email = models.EmailField(blank=False, null=False, verbose_name='Email')
    cliente_phone = models.CharField(max_length=20, blank=False, null=False, verbose_name="Telefone")
    cliente_cpf = models.CharField('CPF/CNPJ', max_length=14, validators=[validate_cpf, MinLengthValidator(11)],
                                   null=False,
                                   blank=False)
    cliente_endereco = models.CharField(max_length=100, blank=False, null=False, verbose_name="Endereço")
    cliente_data = models.DateField(auto_now_add=True, blank=False, null=False, verbose_name="Data de cadastro")

    class Meta:
        verbose_name_plural = "01-Cadastro de Cliente"

    def __str__(self):
        return self.cliente_nome


# -----------------------Veículos--------------------

class Veiculo(models.Model):
    veiculo_tipo = models.ForeignKey(TipoVeiculo, on_delete=models.CASCADE)
    veiculo_data = models.DateField(auto_now_add=True, blank=False, null=True, verbose_name="Data de cadastro")
    veiculo_placa = models.CharField(max_length=10, verbose_name="Placa do veículo", unique=True)
    veiculo_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name='Cliente')
    veiculo_operante = models.BooleanField(default=False, blank=False, null=False, verbose_name='Veículo operante')
    veiculo_descricao = models.TextField(blank=True, null=False, verbose_name='Descrição do Veículo')

    class Meta:
        verbose_name_plural = "05-Criação de Veículo"

    def __str__(self):
        return f'{self.veiculo_placa} - {self.veiculo_cliente.cliente_nome}'


# -----------------------Ordem de serviço--------------------


class OrdemServico(models.Model):
    ordem_codigo = models.IntegerField(verbose_name='Código', unique=True, editable=False)
    ordem_placa = models.ForeignKey(
        Veiculo,
        to_field='veiculo_placa',
        verbose_name="Placa e Cliente do veículo",
        on_delete=models.CASCADE
    )

    ordem_data = models.DateField(
        auto_now_add=True,
        blank=False,
        null=True,
        verbose_name="Data de Cadastro"
    )
    ordem_data_atualizada = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
        verbose_name="Última atualização"
    )
    ordem_classificacao = models.BooleanField(
        default=False,
        blank=False,
        null=False,
        verbose_name="Ordem aberta?"
    )
    ordem_descricao = models.TextField(
        blank=True,
        null=False,
        verbose_name='Descrição do procedimento'
    )
    ordem_grupo_pecas = models.ManyToManyField(
        GrupoPecas,
        verbose_name="Conjunto de Sistema",
        blank=True
    )
    ordem_troca = models.BooleanField(
        default=False,
        blank=False,
        null=False,
        verbose_name="Troca de peça?"
    )
    ordem_valor_servico = models.IntegerField(
        default=0,
        verbose_name='Valor do serviço'
    )
    ordem_peca = models.IntegerField(
        default=0,
        verbose_name='Valor da peça'
    )
    pecas_grupo = models.ManyToManyField(
        PecasVeiculo,
        blank=True,
        verbose_name="Peças trocadas"
    )
    ordem_valor = models.IntegerField(
        default=0,
        verbose_name='Outros Gastos'
    )
    ordem_outros = models.TextField(
        max_length=800,
        blank=True,
        null=False,
        verbose_name='Descrição dos gastos'
    )

    class Meta:
        verbose_name_plural = "06-Ordens de Serviço"

    def __str__(self):
        return str(self.ordem_codigo)

    def save(self, *args, **kwargs):
        if not self.ordem_codigo:
            while True:
                codigo = random.randint(10000, 99999)
                if not OrdemServico.objects.filter(ordem_codigo=codigo).exists():
                    self.ordem_codigo = codigo
                    break

        super().save(*args, **kwargs)

clientes/forms.py
from django import forms
from .models import OrdemServico

class OrdemServicoForm(forms.ModelForm):
    class Meta:
        model = OrdemServico
        fields = '__all__'

clientes/views.py
from django.shortcuts import render
from .forms import OrdemServicoForm
from .models import OrdemServico


def home(request):
    if request.method == "GET":
        lista = OrdemServico.objects.all()

        context = {
            'lista': lista
        }
        return render(request, "home.html", context)
    else:
        form = OrdemServicoForm(request.POST)
        if form.is_valid():
            form.save()


def os(request):
    if request.method == "GET":
        form = OrdemServicoForm()
        context = {
            'form': form
        }
        return render(request, 'formulario_modelform.html', context=context)
    elif request.method == "POST":
        form = OrdemServicoForm(request.POST)
        if form.is_valid():
            form.save()
            form = OrdemServicoForm()
        else:
            context = {
                'form': form
            }
            return render(request, 'formulario_modelform.html', context=context)
    else:
        form = OrdemServicoForm()

    context = {
        'form': form
    }
    return render(request, 'formulario_modelform.html', context=context)

templates/formulario_modelform.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ordem de Serviço</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'form/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'form/css/style.css' %}">
</head>
<body>
<div class="navbar">
    <a href="/admin/">Área Administrativa</a>
</div>
<div class="container">
    <h1>REGISTRE SUA OS</h1>
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.ordem_placa.id_for_label }}">Placa do Veículo:</label>
            {{ form.ordem_placa }}
            {% if form.ordem_placa.errors %}
                <ul class="errors">
                    {% for error in form.ordem_placa.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>



        <div class="form-group">
            <label for="{{ form.ordem_descricao.id_for_label }}">Descrição do Procedimento:</label>
            {{ form.ordem_descricao }}
            {% if form.ordem_descricao.errors %}
                <ul class="errors">
                    {% for error in form.ordem_descricao.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.ordem_grupo_pecas.id_for_label }}">Conjunto de Sistema:</label>
            {{ form.ordem_grupo_pecas }}
            {% if form.ordem_grupo_pecas.errors %}
                <ul class="errors">
                    {% for error in form.ordem_grupo_pecas.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.pecas_grupo.id_for_label }}">Peças Trocadas:</label>
            <select name="pecas_grupo" id="id_pecas_grupo" multiple>
                {% for peca in form.pecas_grupo.field.queryset %}
                    <option value="{{ peca.id }}">{{ peca }}</option>
                {% endfor %}
            </select>
            {% if form.pecas_grupo.errors %}
                <ul class="errors">
                    {% for error in form.pecas_grupo.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="{{ form.ordem_valor_servico.id_for_label }}">Valor do Serviço:</label>
                {{ form.ordem_valor_servico }}
                {% if form.ordem_valor_servico.errors %}
                    <ul class="errors">
                        {% for error in form.ordem_valor_servico.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="form-group col-md-6">
                <label for="{{ form.ordem_peca.id_for_label }}">Valor da Peça:</label>
                {{ form.ordem_peca }}
                {% if form.ordem_peca.errors %}
                    <ul class="errors">
                        {% for error in form.ordem_peca.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.ordem_valor.id_for_label }}">Outros Gastos:</label>
            {{ form.ordem_valor }}
            {% if form.ordem_valor.errors %}
                <ul class="errors">
                    {% for error in form.ordem_valor.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.ordem_outros.id_for_label }}">Descrição dos Gastos:</label>
            {{ form.ordem_outros }}
            {% if form.ordem_outros.errors %}
                <ul class="errors">
                    {% for error in form.ordem_outros.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <input type="submit" value="Salvar Ordem de Serviço">
    </form>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<script src="{% static 'form/js/main.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_pecas_grupo').select2({
            placeholder: 'Selecione as peças',
            allowClear: true,
        });
    });
</script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Raphael Costa" />
        <title>GESTÃO RFID</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'base/assets/favicon.png' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'base/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href=""><img src= "static/assets/img/logo2.png" alt="img"></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="/admin">Área Administrativa</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">TENHA A MELHOR GESTÃO PARA SUA FROTA</h1>
                            <p class="lead text-white-50 mb-4">Otimize sua frota com nosso sistema de gestão: controle, monitoramento e eficiência para alcançar o sucesso!</p>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Features section-->
        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder">Gestão Melhorada</h2>
                        <p>Tenha em suas mãos a gestão de ordem de serviços de cada cliente e de cada máquina!</p>

                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-building"></i></div>
                        <h2 class="h4 fw-bolder">Controle de Datas</h2>
                        <p>Tenha acesso as datas de cada OS criada. Mantenha o controle de seus prazos!</p>

                    </div>
                    <div class="col-lg-4">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>
                        <h2 class="h4 fw-bolder">PowerBI</h2>
                        <p>Integre o banco de dados a tecnologia PowerBI da Microsoft e crie dashboards interativos!</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact section-->
        <section class="bg-light py-5">
            <div class="container px-5 my-5 px-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                    <h2 class="fw-bolder">Entre em contato!</h2>
                    <p class="lead mb-0">Adoraríamos conversar com você!</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <form action="https://formsubmit.co/gestaorfid@gmail.com" method="POST" enctype="text/plain" id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <!-- Nome -->
                            <div class="form-floating mb-3">
                                <input type="name" name="Nome" class="form-control" id="name" placeholder="Enter your name..." data-sb-validations="required" />
                                <label for="name">Nome completo</label>
                                <div class="invalid-feedback" data-sb-feedback="name:required">Escreva seu nome</div>
                            </div>
                            <!-- Email -->
                            <div class="form-floating mb-3">
                                <input type="email" name="email" class="form-control" id="email"  placeholder="name@example.com" data-sb-validations="required,email" />
                                <label for="email">Email</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">Email é necessário</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">Email inválido</div>
                            </div>
                            <!-- Numero de Telefone-->
                            <div class="form-floating mb-3">
                                <input type="tel" name="tel" class="form-control" id="phone" placeholder="(123) 456-7890" data-sb-validations="required" />
                                <label for="phone">Telefone</label>
                                <div class="invalid-feedback" data-sb-feedback="phone:required">É necessário um telefone</div>
                            </div>
                            <!-- Menssagem -->
                            <div class="form-floating mb-3">
                                <input type="text" name="text" class="form-control" id="message" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></input>
                                <label for="message">Mensagem</label>
                                <div class="invalid-feedback" data-sb-feedback="message:required">É preciso uma mensagem...</div>
                            </div>

                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Mensagem enviada com sucesso!</div>
                                    <br />
                                </div>
                            </div>

                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Erro ao enviar!</div></div>

                            <div class="d-grid"><button type="submit" class="btn btn-primary btn-lg disabled" id="submitButton" >Enviar!</button></div>

                        </form>
                    </div>
                </div>
            </div>
        </section>

        <footer class="py-5 bg-dark">
            <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Gestão RFID 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

        <script src="{% static 'base/js/scripts.js' %}"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>